spring:
  datasource:
    # Agregamos el permiso al final separados por un &
    url: jdbc:mysql://localhost:3306/vegetables?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 1234567
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      # 'update' sincroniza tus clases Java con las tablas de MySQL
      ddl-auto: update
    show-sql: true